# This file was auto-generated by Polybuild

include_path_flag := -I
library_path_flag := -L
obj_path_flag := -o
out_path_flag := -o
library_flag := -l
release_dynamic_flag :=
release_static_flag := -static
debug_dynamic_flag :=
debug_static_flag := -static
debug_compilation_flag := -g
debug_link_flag :=
shared_flag := -shared -fPIC
compile_only_flag := -c
link_flag :=
pkg_config_syntax :=
obj_ext := .o
out_ext :=
ifeq ($(OS),Windows_NT)
	include_path_flag := /I
	library_path_flag := /LIBPATH:
	obj_path_flag := /Fo:
	out_path_flag := /Fe:
	library_flag :=
	release_dynamic_flag := /MD
	release_static_flag := /MT
	debug_dynamic_flag := /MDd
	debug_static_flag := /MTd
	debug_compilation_flag := /Zi
	debug_link_flag := /DEBUG
	shared_flag := /LD
	compile_only_flag := /c
	link_flag := /link
	pkg_config_syntax := --msvc-syntax
	obj_ext := .obj
	out_ext := .exe
endif

active_dynamic_flag := $(release_dynamic_flag)
active_static_flag := $(release_static_flag)
active_debug_compilation_flag :=
active_debug_link_flag :=
ifeq ($(MODE),debug)
	active_debug_compilation_flag := $(debug_compilation_flag)
	active_debug_link_flag := $(debug_link_flag)
	active_dynamic_flag := $(debug_dynamic_flag)
	active_static_flag := $(debug_static_flag)
endif

c_compiler := "$(CC)"
cpp_compiler := "$(CXX)"
c_compilation_flags := $(CFLAGS)
cpp_compilation_flags := -Wall -std=c++17 -O3
link_time_flags := $(LDFLAGS)
is_static := false
library_paths :=
libraries :=
pkg_config_libraries :=
define prefix :=
/usr/local/bin
endef

ifeq ($(OS),Windows_NT)
	cpp_compilation_flags := /W3 /std:c++17 /EHsc /O2
	is_static := true
	define prefix :=
C:\Windows\System32
endef
endif

active_linkage_flag := $(active_dynamic_flag)
ifeq ($(is_static),true)
	active_linkage_flag := $(active_static_flag)
endif

c_compilation_flags += $(active_debug_compilation_flag) $(active_linkage_flag)
cpp_compilation_flags += $(active_debug_compilation_flag) $(active_linkage_flag)
link_time_flags += $(active_debug_link_flag) $(library_paths)
ifneq ($(strip $(pkg_config_libraries)),)
	c_compilation_flags += `pkg-config $(pkg_config_syntax) --cflags $(pkg_config_libraries)`
	cpp_compilation_flags += `pkg-config $(pkg_config_syntax) --cflags $(pkg_config_libraries)`
	libraries += `pkg-config $(pkg_config_syntax) --libs $(pkg_config_libraries)`
endif

all: polybuild$(out_ext)
.PHONY: all

obj/build_0$(obj_ext): ./build.cpp .polybuild.mk build.hpp toml.hpp toml/parser.hpp toml/combinator.hpp toml/region.hpp toml/color.hpp toml/result.hpp toml/traits.hpp toml/from.hpp toml/into.hpp toml/version.hpp toml/utility.hpp toml/lexer.hpp toml/macros.hpp toml/types.hpp toml/comments.hpp toml/datetime.hpp toml/string.hpp toml/value.hpp toml/exception.hpp toml/source_location.hpp toml/storage.hpp toml/literal.hpp toml/serializer.hpp toml/get.hpp util.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p "obj"
	@$(cpp_compiler) $(compile_only_flag) "$<" $(cpp_compilation_flags) "$(obj_path_flag)$@"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/main_0$(obj_ext): ./main.cpp .polybuild.mk build.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p "obj"
	@$(cpp_compiler) $(compile_only_flag) "$<" $(cpp_compilation_flags) "$(obj_path_flag)$@"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

objects :=  obj/build_0$(obj_ext) obj/main_0$(obj_ext)
polybuild$(out_ext): .polybuild.mk $(objects) $(static_libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Building $@..."
	@$(cpp_compiler) $(objects) $(static_libraries) $(cpp_compilation_flags) "$(out_path_flag)$@" $(link_flag) $(link_time_flags) $(libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished building $@!"

clean:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Deleting polybuild$(out_ext) and obj..."
	@rm -rf "polybuild$(out_ext)" "obj"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished deleting polybuild$(out_ext) and obj!"
.PHONY: clean

install:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Copying polybuild$(out_ext) to $(prefix)..."
	@cp "polybuild$(out_ext)" "$(prefix)"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished copying polybuild$(out_ext) to $(prefix)!"
.PHONY: install
