# This file was auto-generated by Polybuild

compiler := $(CXX)
compilation_flags := -Wall -std=c++17 -O3
libraries := $(LDLIBS)

default: polybuild
.PHONY: default

obj/main_0.o: ./main.cpp ./toml.hpp ./toml/parser.hpp ./toml/combinator.hpp ./toml/region.hpp ./toml/color.hpp ./toml/result.hpp ./toml/traits.hpp ./toml/from.hpp ./toml/into.hpp ./toml/version.hpp ./toml/utility.hpp ./toml/lexer.hpp ./toml/macros.hpp ./toml/types.hpp ./toml/comments.hpp ./toml/datetime.hpp ./toml/string.hpp ./toml/value.hpp ./toml/exception.hpp ./toml/source_location.hpp ./toml/storage.hpp ./toml/literal.hpp ./toml/serializer.hpp ./toml/get.hpp
	@printf '\033[1m[POLYBUILD]\033[0m Compiling $@ from $<...\n'
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf '\033[1m[POLYBUILD]\033[0m Finished compiling $@ from $<!\n'

polybuild: obj/main_0.o
	@printf '\033[1m[POLYBUILD]\033[0m Building $@...\n'
	@$(compiler) $^ $(compilation_flags) $(libraries) -o $@
	@printf '\033[1m[POLYBUILD]\033[0m Finished building $@!\n'

clean:
	@printf '\033[1m[POLYBUILD]\033[0m Deleting polybuild and obj...\n'
	@rm -rf polybuild obj
	@printf '\033[1m[POLYBUILD]\033[0m Finished deleting polybuild and obj!\n'
.PHONY: clean

install:
	@printf '\033[1m[POLYBUILD]\033[0m Copying polybuild to /usr/local/bin...\n'
	@cp polybuild /usr/local/bin
	@printf '\033[1m[POLYBUILD]\033[0m Finished copying polybuild to /usr/local/bin!\n'
.PHONY: install
