[paths]
output = "polybuild"
source = ["."]
artifact = "obj"
install = "/usr/local/bin"

[options]
compilation-flags = "-Wall -std=c++17 -O3"

[env.OS.Windows_NT.paths]
install = "C:\\Windows\\System32"

[env.OS.Windows_NT.options]
compilation-flags = "/W3 /std:c++17 /EHsc /Ox"
static = true
