# This file was auto-generated by Polybuild

include_path_flag := -I
library_path_flag := -L
obj_path_flag := -o
out_path_flag := -o
library_flag := -l
release_dynamic_flag :=
release_static_flag := -static
debug_dynamic_flag :=
debug_static_flag := -static
debug_compilation_flag := -g
debug_link_flag :=
shared_flag := -shared -fPIC
compile_only_flag := -c
link_flag :=
pkg_config_syntax :=
obj_ext := .o
out_ext := .so
ifeq ($(OS),Windows_NT)
	include_path_flag := /I
	library_path_flag := /LIBPATH:
	obj_path_flag := /Fo:
	out_path_flag := /Fe:
	library_flag :=
	release_dynamic_flag := /MD
	release_static_flag := /MT
	debug_dynamic_flag := /MDd
	debug_static_flag := /MTd
	debug_compilation_flag := /Zi
	debug_link_flag := /DEBUG
	shared_flag := /LD
	compile_only_flag := /c
	link_flag := /link
	pkg_config_syntax := --msvc-syntax
	obj_ext := .obj
	out_ext := .dll
endif

active_dynamic_flag := $(release_dynamic_flag)
active_static_flag := $(release_static_flag)
active_debug_compilation_flag :=
active_debug_link_flag :=
ifeq ($(MODE),debug)
	active_debug_compilation_flag := $(debug_compilation_flag)
	active_debug_link_flag := $(debug_link_flag)
	active_dynamic_flag := $(debug_dynamic_flag)
	active_static_flag := $(debug_static_flag)
endif

c_compiler := "clang"
cpp_compiler := "g++"
c_compilation_flags := -Wall -O2 $(active_debug_compilation_flag) $(include_path_flag)"include" $(shared_flag) $(active_static_flag) `pkg-config $(pkg_config_syntax) --cflags "gstreamer-1.0" "glew"`
cpp_compilation_flags := -Wall -std=c++17 -O2 $(active_debug_compilation_flag) $(include_path_flag)"include" $(shared_flag) $(active_static_flag) `pkg-config $(pkg_config_syntax) --cflags "gstreamer-1.0" "glew"`
link_time_flags := -Wl,--as-needed $(active_debug_link_flag) $(library_path_flag)"vendor lib" $(library_path_flag)"lib"
libraries := $(library_flag)"ssl" $(library_flag)"crypto" `pkg-config $(pkg_config_syntax) --libs "gstreamer-1.0" "glew"`
static_libraries := lib/first.a lib/second.a
prefix := "/tmp/install dir"

ifeq ($(OS),Windows_NT)
	c_compiler := "cl"
	cpp_compiler := "clang-cl"
	c_compilation_flags := /W3 $(active_debug_compilation_flag) $(include_path_flag)"include" $(shared_flag) $(active_dynamic_flag) `pkg-config $(pkg_config_syntax) --cflags "glew"`
	cpp_compilation_flags := /W3 /std:c++17 /O2 $(active_debug_compilation_flag) $(include_path_flag)"include" $(shared_flag) $(active_dynamic_flag) `pkg-config $(pkg_config_syntax) --cflags "glew"`
	link_time_flags := /SUBSYSTEM:WINDOWS $(active_debug_link_flag) $(library_path_flag)"winlib"
	libraries := $(library_flag)"libssl.lib" $(library_flag)"ws2_32.lib" `pkg-config $(pkg_config_syntax) --libs "glew"`
	static_libraries := winlib/first.lib
	prefix := "C:\\Program Files\\Example"
endif

ifeq ($(MODE),debug)
	c_compiler := "clang"
	cpp_compiler := "clang++"
	c_compilation_flags := -Wall -O2 $(active_debug_compilation_flag) $(include_path_flag)"include" $(shared_flag) $(active_static_flag)
	cpp_compilation_flags := -O0 $(active_debug_compilation_flag) $(include_path_flag)"include" $(shared_flag) $(active_static_flag)
	link_time_flags := -Wl,--as-needed $(active_debug_link_flag) $(library_path_flag)"vendor lib" $(library_path_flag)"lib"
	libraries :=
	static_libraries :=
	prefix := "/tmp/install dir"
endif

ifeq ($(OS),Linux)
	c_compiler := "clang"
	cpp_compiler := "g++"
	c_compilation_flags := -Wall -O2 $(active_debug_compilation_flag) $(include_path_flag)"include" $(shared_flag) $(active_dynamic_flag) `pkg-config $(pkg_config_syntax) --cflags "gstreamer-1.0" "glew"`
	cpp_compilation_flags := -Wall -std=c++17 -O2 $(active_debug_compilation_flag) $(include_path_flag)"include" $(shared_flag) $(active_dynamic_flag) `pkg-config $(pkg_config_syntax) --cflags "gstreamer-1.0" "glew"`
	link_time_flags := -Wl,--as-needed $(active_debug_link_flag) $(library_path_flag)"vendor lib" $(library_path_flag)"lib"
	libraries := $(library_flag)"ssl" $(library_flag)"crypto" `pkg-config $(pkg_config_syntax) --libs "gstreamer-1.0" "glew"`
endif

all: bin/example$(out_ext)
.PHONY: all

objects/main_0$(obj_ext): c/main.c .polybuild.mk c/local.h include/common.h include/nested.h
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p "objects"
	@$(c_compiler) $(compile_only_flag) "$<" $(c_compilation_flags) "$(obj_path_flag)$@"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

objects/extra_0$(obj_ext): cpp/extra.cc .polybuild.mk include/common.h include/nested.h
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p "objects"
	@$(cpp_compiler) $(compile_only_flag) "$<" $(cpp_compilation_flags) "$(obj_path_flag)$@"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

objects/main_1$(obj_ext): cpp/main.cpp .polybuild.mk include/common.h include/nested.h cpp/windows.h
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p "objects"
	@$(cpp_compiler) $(compile_only_flag) "$<" $(cpp_compilation_flags) "$(obj_path_flag)$@"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

objects/other_0$(obj_ext): cpp/other.cxx .polybuild.mk include/common.h include/nested.h
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p "objects"
	@$(cpp_compiler) $(compile_only_flag) "$<" $(cpp_compilation_flags) "$(obj_path_flag)$@"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

objects/single_0$(obj_ext): single.c .polybuild.mk
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p "objects"
	@$(c_compiler) $(compile_only_flag) "$<" $(c_compilation_flags) "$(obj_path_flag)$@"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

objects :=  objects/main_0$(obj_ext) objects/extra_0$(obj_ext) objects/main_1$(obj_ext) objects/other_0$(obj_ext) objects/single_0$(obj_ext)
bin/example$(out_ext): .polybuild.mk $(objects) $(static_libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Building $@..."
	@mkdir -p "bin"
	@$(cpp_compiler) $(objects) $(static_libraries) $(cpp_compilation_flags) "$(out_path_flag)$@" $(link_flag) $(link_time_flags) $(libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished building $@!"

clean:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Executing clean prelude: echo cleaning"
	@echo cleaning
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Deleting bin/example$(out_ext) and objects..."
	@rm -rf "bin/example$(out_ext)" "objects"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished deleting bin/example$(out_ext) and objects!"
.PHONY: clean

install:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Copying bin/example$(out_ext) to $(prefix)..."
	@cp "bin/example$(out_ext)" $(prefix)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished copying bin/example$(out_ext) to $(prefix)!"
.PHONY: install
