# This file was auto-generated by Polybuild

include_path_flag := -I
library_path_flag := -L
obj_path_flag := -o
out_path_flag := -o
library_flag := -l
release_dynamic_flag :=
release_static_flag := -static
debug_dynamic_flag :=
debug_static_flag := -static
debug_compilation_flag := -g
debug_link_flag :=
shared_flag := -shared -fPIC
compile_only_flag := -c
link_flag :=
pkg_config_syntax :=
obj_ext := .o
out_ext :=
ifeq ($(OS),Windows_NT)
	include_path_flag := /I
	library_path_flag := /LIBPATH:
	obj_path_flag := /Fo:
	out_path_flag := /Fe:
	library_flag :=
	release_dynamic_flag := /MD
	release_static_flag := /MT
	debug_dynamic_flag := /MDd
	debug_static_flag := /MTd
	debug_compilation_flag := /Zi
	debug_link_flag := /DEBUG
	shared_flag := /LD
	compile_only_flag := /c
	link_flag := /link
	pkg_config_syntax := --msvc-syntax
	obj_ext := .obj
	out_ext := .exe
endif

active_dynamic_flag := $(release_dynamic_flag)
active_static_flag := $(release_static_flag)
active_debug_compilation_flag :=
active_debug_link_flag :=
ifeq ($(MODE),debug)
	active_debug_compilation_flag := $(debug_compilation_flag)
	active_debug_link_flag := $(debug_link_flag)
	active_dynamic_flag := $(debug_dynamic_flag)
	active_static_flag := $(debug_static_flag)
endif

c_compiler := "$(CC)"
cpp_compiler := "$(CXX)"
c_compilation_flags := $(CFLAGS) $(active_debug_compilation_flag) $(active_dynamic_flag)
cpp_compilation_flags := $(CXXFLAGS) $(active_debug_compilation_flag) $(active_dynamic_flag)
link_time_flags := $(LDFLAGS) $(active_debug_link_flag)
libraries :=

all: app$(out_ext)
.PHONY: all

obj/main_0$(obj_ext): c/main.c .polybuild.mk c/local.h
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p "obj"
	@$(c_compiler) $(compile_only_flag) "$<" $(c_compilation_flags) "$(obj_path_flag)$@"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

objects :=  obj/main_0$(obj_ext)
app$(out_ext): .polybuild.mk $(objects) $(static_libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Building $@..."
	@$(c_compiler) $(objects) $(static_libraries) $(c_compilation_flags) "$(out_path_flag)$@" $(link_flag) $(link_time_flags) $(libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished building $@!"

clean:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Deleting app$(out_ext) and obj..."
	@rm -rf "app$(out_ext)" "obj"
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished deleting app$(out_ext) and obj!"
.PHONY: clean

install:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Copying app$(out_ext) to $(prefix)..."
	@cp "app$(out_ext)" $(prefix)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished copying app$(out_ext) to $(prefix)!"
.PHONY: install
